version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: turtlesoup-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/app/db
      - ./data:/app/data
    env_file:
      - ./backend/models/.env

  frontend:
    build:
      context: ./frontend
    container_name: turtlesoup-frontend
    ports:
      - "8080:80"
